# syntax=docker/dockerfile:1

FROM golang:1.17-alpine AS build

WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 go build -o /raduty-s

## deploy part

FROM gcr.io/distroless/base

WORKDIR /

COPY --from=build /raduty-s /

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT [ "/raduty-s" ]